# используем язык Java.
language: java
jdk:
  - openjdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database test_item_tracker;' -U postgres
  - psql -c 'create database test_vacparser;' -U postgres

env:
  USED_DB_PROFILE=travis

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
# отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      - denispkv@yandex.ru
    on_success: never # default: change
    on_failure: always # default: change
